### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by BagchiMB** [pujanb96/Streamy-App#1]
Hey, your app works great, can you help me deploying this app

**Comment by heisenbug-io** [comment]
Hi @BagchiMB, Please refer to the readme file provided. You can use NPM and import all the required packages. You will need to get a GAPI key as well for the Login to work. Let me know if you are stuck on a particular section

**Comment by BagchiMB** [comment]
No man, actually all of this is good.... I was talking about actual deployment over the internet
Do you have any idea for that?

**Comment by heisenbug-io** [comment]
If you want to make this app live you'll need to configure the apache or Nginx to be an RTMP server. Refer to this video on youtube on how to configure Nginx - https://www.youtube.com/watch?v=1qH2bo7NHzg

Also, You will have to host Node Media Server which can be on the same server(different port). 
Lastly, the JSON server. You can modify the code to have it query a database which would be more robust for a live app. I used JSON server for development purposes.
